name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

env:
  CARGO_TERM_COLOR: always

jobs:
  udeps:
    name: Check unused dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DKIN_CLOUD_TOKEN }}
          submodules: true
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install udeps
        run: cargo install cargo-udeps --locked
      - name: Run udeps
        run: cargo +nightly udeps

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libasound2-dev
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: cargo check --all --examples --tests

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libasound2-dev
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add rustfmt
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libasound2-dev
      - run: rustup component add clippy
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: cargo clippy --all -- -D warnings
